# Generated by Django 5.2.17 on 2026-09-12 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_partida', models.CharField(max_length=100)),
                ('ponto_chegada', models.CharField(max_length=100)),
                ('dias', models.CharField(choices=[('seg_sex', 'Segunda à Sexta'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='seg_sex', max_length=10)),
                ('horario_saida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InscricaoLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruyrotas.linha')),
            ],
        ),
    ]
