# Generated by Django 5.2.17 on 2026-09-12 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyrotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricaolinha',
            name='linha',
        ),
        migrations.RenameField(
            model_name='inscricaolinha',
            old_name='data_inscricao',
            new_name='data_cadastro',
        ),
        migrations.AddField(
            model_name='inscricaolinha',
            name='dias_viagem',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaolinha',
            name='horario_linha',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaolinha',
            name='local_chegada',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricaolinha',
            name='local_partida',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricaolinha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Linha',
        ),
    ]
