# Generated by Django 5.2.17 on 2026-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyrotas', '0003_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('comprovante', models.FileField(upload_to='comprovantes/')),
            ],
        ),
    ]
